baseURL: "https://gavilanes.no"
languageCode: "en-us"
title: "Vilma Gavilanes Official"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1

#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "VILMA GAVILANES"
  description: Vilma Gavilanes - Offisielt nettsted // Página oficial
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable
    disableSearch: true

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hola, me llamo / Hi, mitt navn er"
    title: "Vilma Gavilanes"
    subtitle: "Vinddrag - Ráfagas de viento"
    content: "Fortellinger, politisk poesi // Historias cortas, poesía política"
    image: /images/20210409_115154.jpg
#    button:
#      enable: true
#      name: "Resume"
#      url: "#"
#      download: true
#      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-facebook-f
          url: https://www.facebook.com/people/Vilma-Gavilanes/100084311889810/

  # About
  about:
    enable: true
    title: "Om / Acerca de"
    image: "/images/20210409_115154.jpg"
    content: |-
      **Om Vilma**
      Uttrykk gjennom kunst har vært en reise med møter, oppdagelser og dype refleksjoner.
      Naturen, familien, venner, samfunnet i seg selv, har vært en permanent inspirasjonskilde for skapelsen av mine kunstnerisk projekter og det blir slik i framtiden også.
      I begynnelsen av den kreative handlingen dukker det opp bevegelse, dans som første uttrykksform, deretter ord og performance gjennom teater, for senere å utvikle min egen uttrykksform, forene flere scenekunstner i samklang, et uttrykk som deles med flere kunstnere fra forskjellige land, dette i tverrfaglige prosjekter av egne kreasjoner innen musikk, poetiske tekster, koreografi, skuespill, fotografi, malerier og til og med å være skapere av kostymer og ofte sett i koreografier.
      En del av den kunstneriske praksisen har også vært å være danselærer for barn, ungdom og voksne. Inkludering av alle menneskelige grupper uansett kjønn, bakgrunn, tro, opprinnelse, eller tilstand, har vært en del av min scenisk kunstnerisk arbeid for  å nevne min visjon som grunnleggende tema i mine  kreasjoner. 
      Poesi har ofte vært en inspirasjonskilde for kroppsbevegelser, det samme har musikk og fotografi, og med disse inspirerende kunstnere har det blitt utviklet sceniske bilder som har fortalt menneskelige historier på den tiden.
      Den utøvende kunstneren av bevegelser er ikke bare en danser, jeg er mer enn dette, jeg er forfatter av tekster, av sceniske prosesser , poetiske prosesser og ikke minst menneskelige møter.
      Å jobbe med parallelle prosjekter er det grunnleggende behovet for å fortsette å skape med gjensidig inspirasjon, den menneskelige skaper handlingen, skapelsen som aldri blir født alene.
      Hvert prosjekt som ble gjennomført eller skal gjennomføres hadde og vil ha en intensjon, en intensjon om å kommunisere et spesifikt budskap om hva som har blitt oppfattet som av menneskelig interesse, basert på atferd i de ulike menneskelige kulturene. Her tas politiske, filosofiske, sosiale aspekter generelt i betraktning.
      Å skrive er et grunnleggende menneskelig behov og det er dette behovet som tar form i denne skapelsesprosessen hvor nye installasjoner eller scenekunst skal ta form dag for dag.
      Velkommen til min lille verden. Jeg er opptatt av mange uttrykksformer i kunst. Jeg startet min kunstnerkarriere i det profesjonelle miljøet i Ecuador som danser og senere som koreograf. Helt siden 1991 har jeg uttrykt meg i en fargerik kombinasjon av bilder, musikk, dans og poesi i såkalte samtidskunst i multimedia prosjekter både i Norge og i Ecuador.                                     

      **Acerca de Vilma**
      La expresión a través de las artes ha sido un viaje de encuentros, descubrimientos y reflexiones profundas.
      La naturaleza, la familia, los amigos, la sociedad en sí, han sido una  fuente permanente de inspiración para la creación. 
      Al inicio del acto creativo aparece el movimiento, la danza como la primera forma de expresión, luego la palabra y la actuación a través del teatro, para luego desarrollar una forma propia de expresión,  uniendo varias artes escénicas al unísono, expresión compartida con artista de diversos países, esto en proyectos multidisciplinarios de creaciones propias en la música, textos poéticos, coreografías, actuación, fotografía, pinturas e incluso siendo creadores al unísono de vestuarios y muchas veces escenografías.
      Parte de la práctica artística ha sido también ser maestra de danza para niños, adolescentes y adultos. La inclusión de todo grupo humano  a pesar de su sexo, creencia, nacionalidad o estado fiísico al trabajo artístico escénico es  tema fundamental en mis creaciones.
      La poesía ha sido muchas veces fuente de inspiración al movimiento corporal, al igual que la música, la fotografía, y con estas artes inspiradoras se han ido desarrollando imágenes escénicas que han contado historias humanas en su momento.
      La artista ejecutora de movimientos no es solamente un danzante o bailarín, se es más que  esto, se es autor de textos, de procesos escénicos, poéticos y de no menos de encuentros humanos. 
      Trabajar en proyectos paralelos es la necesidad básica para seguir creando con inspiraciones mutuas, el acto humano de la creación, creación que jamás nace sola.
      Cada proyecto ejecutado  o por ejecutar tuvo y tendrá una intención, intención de comunicar un mensaje concreto de lo que se percibe o se ha percibido de lo que es de interés humano, basado en comportamientos en las diversas culturas humanas. Aquí se toman en cuenta aspectos políticos, filosóficos, sociales en general.  
      El escribir es una necesidad básica del ser humano y  es esta necesidad que va tomando forma en este proceso de creación donde nuevas instalaciones o artes escénicas van a ir tomando forma día a día.

    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"


  # projects
  projects:
    enable: true
    title: "Prosjekter // Proyectos"
    items:
      - title: Vinddrag
        content: 
          Jeg leverer her en fargerike blanding av tekster som gjerne kan kalles «politiske vers» om å vandre og flytte, om kjærlighet og om det å være menneske som del av naturen.
          Ordene kan ta deg til en reise hvor du vil bli kjent med steder, som du kanskje vil forandre vinkel i den formen du ser de stedene framover. Ordene kan  røre deg igjen og igjen i den fine retningen hvor vi menneske kan bli en del av helheten. Ta deg tid til den reisen og bli med

        image: /images/projects/cover.png
#        featured:
#          name: Demo
#          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
 #       links:
 #         - icon: fa fa-envelope
 #           url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
 #         - icon: fab fa-github
 #           url: https://github.com/gurusabarish/hugo-profile
 #         - icon: fab fa-twitter
 #           url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: Ta gjerne kontakt // Escríbeme
    email: literatura1humana1@gmail.com
    btnName: E-post // Correo electrónico

  footer:
    recentPosts: false
    socialNetworks:
 #     github: https://github.com
 #     linkedin: https://linkedin.com
 #     twitter: https://twitter.com
 #     instagram: https://instagram.com
      facebook: https://facebook.com
